### ISSUE TITLE
Bug in poligon overlay

### ISSUE THREAD

**Issue by lselzer** [Martin-Jung/LecoS#1]
Hello, I'm having the same bug as here http://hub.qgis.org/issues/14700#change-69751 
I would have posted there but I can't sign up because the sign up page has been under maintenance over the last three days.

I got this error:
`2016-05-06T13:55:56	1	Traceback (most recent call last):
			  File "C:/Users/lucia/.qgis2/python/plugins\LecoS\lecos_dlg.py", line 872, in accept
			    err, r = bat.go(cmd,cl,cellsize,None,rasE)
			  File "C:/Users/lucia/.qgis2/python/plugins\LecoS\landscape_polygonoverlay.py", line 151, in go
			    array = self.getClipArray(poly)
			  File "C:/Users/lucia/.qgis2/python/plugins\LecoS\landscape_polygonoverlay.py", line 342, in getClipArray
			    premask = self.imageToArray(rasterPoly)
			  File "C:/Users/lucia/.qgis2/python/plugins\LecoS\landscape_polygonoverlay.py", line 249, in imageToArray
			    a=numpy.fromstring(i.tobytes(),'b')
			  File "C:\PROGRA~1\QGISES~1\apps\Python27\lib\site-packages\PIL\Image.py", line 512, in __getattr__
			    raise AttributeError(name)
			AttributeError: tobytes
			`

And I have updated numpy and (after great pain) scipy
`
import numpy

numpy.__version__

'1.11.0'

import scipy

scipy.__version__

'0.17.0'

import Image

Image.VERSION

'1.1.7'`

I cannot figure out why it doesn't work.

**Comment by lselzer** [comment]
I figured out why it doesn't work. Image class doesn't have a [tobytes ](http://effbot.org/imagingbook/image.htm#tag-Image.Image.tostring)method.
 I tried fixing it by changing tostring. Now there no error but it doesn't produce any useful output.

**Comment by Martin-Jung** [comment]
Confirmed.
It appears as if the tobytes function was kicked out of the official PIL development stream recently (*great*).
As an alternative there i a fork of PIL called Pillow, which still has the [function](http://pillow.readthedocs.io/en/3.1.x/reference/Image.html#PIL.Image.Image.tobytes).

Will see what I can do... ughh...

**Comment by Martin-Jung** [comment]
Hey, Contrary to what you said I tried out the **tostring** function and the calculation worked for me in a test dataset?
Jut pushed an update. Copy the polygon_overlay.py file into your install and report back please

**Comment by lselzer** [comment]
Yes,  it is fixed. What it doesn't work is when the grid extendes outside the raster. I will open another issue for that.
