### ISSUE TITLE
No results - stalling and delays - vector overlay

### ISSUE THREAD

**Issue by technoautotroph** [Martin-Jung/LecoS#11]
I'm trying to collect data along highway segments in northern Alberta. I took vector data from ABMI (http://www.abmi.ca/home.html) and rasterized this to work within LecoS. I had success in early attempts to extract data using the vector overlay function. The road segments are mortality hot spots and cold spots estimated using KDE+ software. I selected the center of each segment to create a 500 m circular buffer to sample the surrounding landscape. I have other raster layers that I'm hoping to use in my summary analysis and will be expanding the sampling to different buffer sizes.

Everything was working in early trials with LecoS. I saved my workspace and the next day found that I could no longer extract LecoS metrics. I went through the entire process of rasterizing, projecting, and clipping the data to see if going from scratch would work. I tried uninstalling and re-installing LecoS, but this has not solved my problem. I left it running overnight - still no table is generated. I've kept the analysis simple by selecting only one metric at a time.

I'm using QGIS V. 2.18.21. LecoS prompts a response in the bottom left of my workspace "Land cover calculated for feature 58 out of 58 (0 impossible)". I clipped the raster in an attempt to make the analysis space smaller. However, nothing happens after this. I've tried saving to a file, adding table to workspace, and save int he attribute table - none of these options are working. 

I've uploaded my raster and the buffer into Dropbox to see if I someone can try to execute and recreate the error. The vector data came from ABMI - so it is projected in Alberta 10-TM (Forest) EPSG:3400, NAD83.

https://www.dropbox.com/sh/uuzv8iw6ek09afd/AABwAGkBDBXLH3sfawm5ItxLa?dl=0

Thank you!

**Comment by technoautotroph** [comment]
UPDATE: I clicked on the option to append the data to the Attribute Table. This worked on one trial occasion, but the excel file is blank. I had to re-open the vector file to see the appended data do the attribute table.

**Comment by Martin-Jung** [comment]
Hi,

Thanks for the detailed report and test data. 
I had a quick look at your data, however I also don't have much time available these days to really dig into finding the error/bug.

Some findings:
* When I loaded the raster and polygon file, I had to reproject the raster before being able to run any analysis
* When saving to a text/table output, Lecos returns an Error to me. Sth. seems to be wrong with UID identifier

![image](https://user-images.githubusercontent.com/3788377/42999198-b8b0a14c-8c14-11e8-9b47-508424c98f1e.png)

* When I added the result to the attribute table, It generally worked. **Notice that new attribute columns won't show up in the attribute table directly. The file must be removed from the QGIS table of contents and loaded again** This is a general problem with *.dbf files in the ESRI shapefile format which do not support on-the-fly updating.

* If the graphical interface continues to make problems, try out the processing interface to the LecoS tools. Saving the output as table works here (uncheck "raster classified" to calculate overall or per class).

![image](https://user-images.githubusercontent.com/3788377/42999497-ea0f1ad8-8c15-11e8-8c5e-b96f113e9f07.png)

* The whole computation on the test data set takes me fewer than 10s. If your computer takes considerably longer, you might want to consider running it on a bigger GIS workstation.

**Comment by technoautotroph** [comment]
Thanks! This worked - quick output. I'm very excited about your project. I've been studying LecoS for a couple of years now in relation to my research and while learning QGIS. My capabilities have advanced in the past few years to the point where I can produce some interesting data. I hope that you continue to work with LecoS as Fragstats is no longer being supported in the latest ArcGIS updates and this is open access. It's a super valuable tool for ecologists and wildlife managers. I want to give you my thanks and praise for this! It is a great project and I think that this will only grow. Hopefully you can receive funding and support to keep this project alive. I'm curious to know what is keeping you busy these days - are you moving onto new related projects??

**Comment by Martin-Jung** [comment]
Thanks and happy to hear that it has been useful for you ;)
I'm currently writing up my PhD thesis and will be job-searching afterwards. I developed LecoS back when I was still an undergraduate student thriving to understand how landscape metrics work. Therefore it has certainly been a while since I last worked on it.
Might expand it a but further if I find time doing so. There is also the upgrade to QGIS 3 that still needs to be done at some point...
