### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by mrobins18** [Martin-Jung/LecoS#19]
Hello,

Where can I find information on the newest release of LecoS (version 3.0). I am trying to use it with QGIS 3.6.3 but am encountering errors when I try to run applications with the plugin. 

I know you need to do custom install for QGIS and  include scimpy, numpy, and PIL with the download. 

I did that but noticed there were 2 versions of these add-ons - one for python and another for python 3? Does it make a difference which I include and could this be the source of my errors?

If anyone familiar with the recent LocoS release has any recommendations it would be much appreciated. 

Thanks in advance!

**Comment by Martin-Jung** [comment]
QGIS 3.X uses python 3 as underlying version, while QGIS 2.X used python 2.
If you encounter any bugs, then please post them with a detailed error report (with screenshots and testing data to reproduce the errors) as issue.
