### ISSUE TITLE
 Plugin causes Minidump on QGIS exit

### ISSUE THREAD

**Issue by Martin-Jung** [Martin-Jung/LecoS#4]
This is a known issue that has been repoted a while ago.
Still don't know how to fix it...

---

Migrated from hub.qgis.org:

I have found that LecoS causes QGIS to write a minidump every time I close the program. This happened on two computers. Once I removed the plugin, the minidumps stopped.
Note that it is not enough to disable the plugin. It must be removed to alleviate the problem.
- [ ] Figure out why QGIS writes a minidump
- [ ] Fix the problem

**Comment by capndave** [comment]
I have the same issue. Although several people mention uninstalling plugins I cannot figure out how to do so, deleting and reinstalling doesn't help.

**Comment by Martin-Jung** [comment]
@capndave You have to delete the plugin from your plugin profile folder. If that also doesn't help then the minidump is not caused by LecoS.
I have seen it occuring with other plugins too and it seem to be related to the gdal libraries I assume... ?

**Comment by gioman** [comment]
@Martin-Jung this issue seems fixed with the latest gdal and python-gdal updates in osgeo4w.

**Comment by Martin-Jung** [comment]
Awesome! Another reason to update. Thanks for reporting 👍
