### ISSUE TITLE
Processing interface raises an error on Windows machines

### ISSUE THREAD

**Issue by domlysz** [Martin-Jung/LecoS#6]
Hi,

QGIS 2.16.3 on Windows, processing 2.12.99

I'm not able to display any user interface, all tools return one of these 2 errors

```
\lecos_sextantealgorithms.py", line 1104, in processAlgorithm
nodata = lcs.f_returnNoDataValue(str(inputFilename)) # Get Nodata-value
AttributeError: 'NoneType' object has no attribute 'f_returnNoDataValue'
```

```
\lecos_sextantealgorithms.py", line 162, in processAlgorithm
what = self.w[self.getParameterValue(self.WHAT)]
TypeError: list indices must be integers, not NoneType
```

I have no error on Linux.

**Comment by Martin-Jung** [comment]
I fail to reproduce your problem and think it is related to whatever input data you are using. Please attach a small subset of your data to reproduce the error.

Your first error also tells me that whatever raster data you are using has no properly encoded NoData value -- _'NoneType'_ (which is necessary to exclude cells with nodata from all metrics).
My windows machine version (QGIS 2.16.3 and processing 2.12.99 ) works without issues.

**Comment by domlysz** [comment]
Thanks for your answer,

I have no particular data to attach because I can't start any tool at all. For now I just double click on a tool name in processing in order to display the GUI, specify my inputs/outputs and start the process but the error message appear before the interface can be displayed (and so before I can choose an input data). I appears even if there is no layers loaded in QGIS.

I found myself the error message ambiguous because it suggest the process was started but its not the case. It's like it run immediately the process before I can setup any parameters.

Hope I'm understandable, sorry for my poor english.

**Comment by Martin-Jung** [comment]
How did you install QGIS on Windows?
The only way how LecoS can work here is by using the OSGEO4W and advanced install.
Again. I sadly can not get to the bottom of this. Allthough I have the same QGIS and processing version on Windows as you, I can use the plugin freely. Ether through the menu: Menu -> raster -> Landscape ecology or via the Processing toolbox.
If I double click on a processing tool it opens just as expected :)
Screenshot:
![screen](https://cloud.githubusercontent.com/assets/3788377/19497935/84a8234c-9586-11e6-9324-65bf15791807.png)

**Comment by domlysz** [comment]
I always use OSGEO4W to handle dependency but you're right it seems it come from my install, I will try to investigate deeply tomorrow.

**Comment by domlysz** [comment]
Finally solved the problem making a new fresh install of QGIS.

Thanks for the help
