### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by technoautotroph** [Martin-Jung/LecoS#9]
I’m very interested in the application of this software for my research into amphibian populations in northern British Columbia. I accessed LiDAR and forest cover data from the following source:

https://landcover.usgs.gov/glc/TreeCoverDescriptionAndDownloads.php

and

http://glad.umd.edu/gladmaps/globalmap.php#

This data was used with LecoS software in the following publication:

https://wwwnc.cdc.gov/eid/article/22/2/15-0656_article

I have QGIS 2.18.12 installed on my Windows 10 Pro computer. I believe that Nimby is installed as a default with this version?

I receive the following error each time I attempt to obtain information from the forest cover data set:
```

2017-09-29T08:25:33	1	Traceback (most recent call last):
			  File "C:/Users/mthompson/.qgis2/python/plugins\LecoS\lecos_dlg.py", line 128, in setNoData
			    band = raster.GetRasterBand(1)
			AttributeError: 'NoneType' object has no attribute 'GetRasterBand'
			
2017-09-29T08:25:44	1	Traceback (most recent call last):
			  File "C:/Users/mthompson/.qgis2/python/plugins\LecoS\lecos_dlg.py", line 128, in setNoData
			    band = raster.GetRasterBand(1)
			AttributeError: 'NoneType' object has no attribute 'GetRasterBand'
			
2017-09-29T08:27:06	1	Traceback (most recent call last):
			  File "C:/Users/mthompson/.qgis2/python/plugins\LecoS\lecos_dlg.py", line 320, in accept
			    classes, array = lcs.f_landcover(rasterPath,nodata)
			  File "C:/Users/mthompson/.qgis2/python/plugins\LecoS\landscape_statistics.py", line 134, in f_landcover
			    array =  band.ReadAsArray()
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal.py", line 2441, in ReadAsArray
			    callback_data = callback_data)
			  File "C:\PROGRA~2\QGIS2~1.18\apps\Python27\lib\site-packages\osgeo\gdal_array.py", line 340, in BandReadAsArray
			    buf_obj = numpy.empty([buf_ysize,buf_xsize], dtype = typecode)
			MemoryError
```

I’m hoping that you might be able to provide some insight into my issues.

Thank you!!

**Comment by Martin-Jung** [comment]
You need to have numpy, scipy and PIL (python imaging library) installed. Numpy comes with OSGEO gdal (and therefore also with QGIS) but the other two libraries need to be installed specifically during the installation process (advanced installation).

However a memoryerror usually indicates that you don't have enough memory as LecoS loads the entire raster file into the machines memory. So if your raster is larger than the memory on your machine, then you will get errors like these. Also note that LecoS is pretty inefficient with very large datasets (I developed it years ago for raster layers usually of about 50-100 MB !).
**Try and crop your raster layer to a small test area and see if runs. If it does you might want to consider serializing your processing framework in smaller parts.**

**Comment by technoautotroph** [comment]
Thank you! I was trying to find a way to install the other two libraries and thought they might also have been defaulted into the latest QGIS as I couldn't locate them in the plugins. I'll try to re-install with the advanced option.

**Comment by technoautotroph** [comment]
Another issue that I discovered is that the raster no value had to be set properly. It was simple to do under Raster > Conversion > Translate. I set no data to 0 and had to reload this in. Otherwise, no data has no value and I think this will be an issue for LecoS. My raster image is trimmed and I'm operating with a speedy computer - so I'll assume that this is a problem with the plugins.

**Comment by technoautotroph** [comment]
Ok...I used the advanced install and made certain that numpy, scipy, and PIL were installed. I used the OSGeo4W Network Installer and selected each one of these along with QGIS 2.18.13. I get the following error:
```

2017-09-29T09:44:22	1	Traceback (most recent call last):
			  File "C:/Users/mthompson/.qgis2/python/plugins\LecoS\lecos_dlg.py", line 320, in accept
			    classes, array = lcs.f_landcover(rasterPath,nodata)
			  File "C:/Users/mthompson/.qgis2/python/plugins\LecoS\landscape_statistics.py", line 134, in f_landcover
			    array =  band.ReadAsArray()
			  File "C:\OSGeo4W\apps\Python27\lib\site-packages\osgeo\gdal.py", line 2441, in ReadAsArray
			    callback_data = callback_data)
			  File "C:\OSGeo4W\apps\Python27\lib\site-packages\osgeo\gdal_array.py", line 340, in BandReadAsArray
			    buf_obj = numpy.empty([buf_ysize,buf_xsize], dtype = typecode)
			MemoryError
```

The raster is clipped to a small study area - so I'm skeptical of the MemoryError and wondering if there is something else going on here?

**Comment by technoautotroph** [comment]
I solved the issue! I clipped the raster, but I had to select the option to:

> Crop the extent of the target dataset to the extent of the cutline.

Everything is working now! Very excited to move forward. Thank you!!
